### PR TITLE
Add Eq and Show instances

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by puffnfresh** [comment]
Some more which would be useful:
- [ ] Ord
- [ ] Semigroup

**Comment by paf31** [comment]
All of these can just be written using [`absurd`](https://github.com/puffnfresh/purescript-void/blob/369fabe59b8a75cb84a0198da4a07348cdd2bb45/src/Data/Void.purs#L10), yes?

**Comment by paf31** [comment]
Also :+1:

**Comment by puffnfresh** [comment]
@paf31 I guess strictness means they're equivalent to absurd, didn't consider that.

**Comment by joneshf** [comment]
Thanks!

**Pull request merged**
